<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ecs_cus_jy_country`;");
E_C("CREATE TABLE `ecs_cus_jy_country` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `x_code` varchar(20) DEFAULT NULL,
  `x_cname` varchar(100) DEFAULT NULL,
  `x_ename` varchar(100) NOT NULL,
  `def` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=260 DEFAULT CHARSET=utf8");
E_D("replace into `ecs_cus_jy_country` values('1','728','南苏丹','South Sudan','0');");
E_D("replace into `ecs_cus_jy_country` values('2','729','苏丹','Sudan','0');");
E_D("replace into `ecs_cus_jy_country` values('3','002','大西洋群岛','Atlantic Ocean Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('4','004','阿富汗','Afghanistan','0');");
E_D("replace into `ecs_cus_jy_country` values('5','008','阿尔巴尼亚','Albania','0');");
E_D("replace into `ecs_cus_jy_country` values('6','010','南极洲','Antarctica','0');");
E_D("replace into `ecs_cus_jy_country` values('7','012','阿尔及利亚','Algeria','0');");
E_D("replace into `ecs_cus_jy_country` values('8','016','美属萨摩亚','American Samoa','0');");
E_D("replace into `ecs_cus_jy_country` values('9','020','安道尔','Andorra','0');");
E_D("replace into `ecs_cus_jy_country` values('10','024','安哥拉','Angola','0');");
E_D("replace into `ecs_cus_jy_country` values('11','028','安提瓜和巴布达','Antigua and Barbuda','0');");
E_D("replace into `ecs_cus_jy_country` values('12','031','阿塞拜疆','Azerbaijan','0');");
E_D("replace into `ecs_cus_jy_country` values('13','032','阿根廷','Argentina','0');");
E_D("replace into `ecs_cus_jy_country` values('14','036','澳大利亚','Australia','0');");
E_D("replace into `ecs_cus_jy_country` values('15','040','奥地利','Austria','0');");
E_D("replace into `ecs_cus_jy_country` values('16','044','巴哈马','Bahamas','0');");
E_D("replace into `ecs_cus_jy_country` values('17','048','巴林','Bahrain','0');");
E_D("replace into `ecs_cus_jy_country` values('18','050','孟加拉','Bangladesh','0');");
E_D("replace into `ecs_cus_jy_country` values('19','051','亚美尼亚','Armenia','0');");
E_D("replace into `ecs_cus_jy_country` values('20','052','巴巴多斯','Barbados','0');");
E_D("replace into `ecs_cus_jy_country` values('21','056','比利时','Belgium','0');");
E_D("replace into `ecs_cus_jy_country` values('22','060','百慕大','Bermuda','0');");
E_D("replace into `ecs_cus_jy_country` values('23','064','不丹','Bhutan','0');");
E_D("replace into `ecs_cus_jy_country` values('24','068','玻利维亚','Bolivia','0');");
E_D("replace into `ecs_cus_jy_country` values('25','070','波斯尼亚和黑塞哥维那','Bosnia and Herzegovina','0');");
E_D("replace into `ecs_cus_jy_country` values('26','072','博茨瓦纳','Botswana','0');");
E_D("replace into `ecs_cus_jy_country` values('27','074','布维岛','Bouvet Island','0');");
E_D("replace into `ecs_cus_jy_country` values('28','076','巴西','Brazil','0');");
E_D("replace into `ecs_cus_jy_country` values('29','084','伯利兹','Belize','0');");
E_D("replace into `ecs_cus_jy_country` values('30','086','英属印度洋领土','British Indian Ocean Territory','0');");
E_D("replace into `ecs_cus_jy_country` values('31','090','所罗门群岛','Solomon Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('32','092','英属维尔京群岛','British Virgin Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('33','096','文莱','Brunei Darussalam','0');");
E_D("replace into `ecs_cus_jy_country` values('34','100','保加利亚','Bulgaria','0');");
E_D("replace into `ecs_cus_jy_country` values('35','104','缅甸','Myanmar','0');");
E_D("replace into `ecs_cus_jy_country` values('36','108','布隆迪','Burundi','0');");
E_D("replace into `ecs_cus_jy_country` values('37','112','白俄罗斯','Belarus','0');");
E_D("replace into `ecs_cus_jy_country` values('38','116','柬埔寨','Cambodia','0');");
E_D("replace into `ecs_cus_jy_country` values('39','120','喀麦隆','Cameroon','0');");
E_D("replace into `ecs_cus_jy_country` values('40','124','加拿大','Canada','0');");
E_D("replace into `ecs_cus_jy_country` values('41','132','佛得角','Cape Verde','0');");
E_D("replace into `ecs_cus_jy_country` values('42','136','开曼群岛','Cayman Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('43','140','中非','Central Africa','0');");
E_D("replace into `ecs_cus_jy_country` values('44','142','休达','Ceuta','0');");
E_D("replace into `ecs_cus_jy_country` values('45','144','斯里兰卡','Sri Lanka','0');");
E_D("replace into `ecs_cus_jy_country` values('46','148','乍得','Chad','0');");
E_D("replace into `ecs_cus_jy_country` values('47','152','智利','Chile','0');");
E_D("replace into `ecs_cus_jy_country` values('48','156','中国','China','1');");
E_D("replace into `ecs_cus_jy_country` values('49','158','中国台湾','Taiwan(CHINA)','0');");
E_D("replace into `ecs_cus_jy_country` values('50','162','圣诞岛','Christmas Island','0');");
E_D("replace into `ecs_cus_jy_country` values('51','166','科科斯（基林）群岛','Cocos (Keeling) Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('52','170','哥伦比亚','Colombia','0');");
E_D("replace into `ecs_cus_jy_country` values('53','174','科摩罗','Comoros','0');");
E_D("replace into `ecs_cus_jy_country` values('54','175','马约特','Mayotte','0');");
E_D("replace into `ecs_cus_jy_country` values('55','178','刚果（布）','Congo-Brazzaville','0');");
E_D("replace into `ecs_cus_jy_country` values('56','180','刚果（金）','Congo-Kinshasa','0');");
E_D("replace into `ecs_cus_jy_country` values('57','184','库克群岛','Cook Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('58','188','哥斯达黎加','Costa Rica','0');");
E_D("replace into `ecs_cus_jy_country` values('59','191','克罗地亚','Croatia','0');");
E_D("replace into `ecs_cus_jy_country` values('60','192','古巴','Cuba','0');");
E_D("replace into `ecs_cus_jy_country` values('61','196','塞浦路斯','Cyprus','0');");
E_D("replace into `ecs_cus_jy_country` values('62','203','捷克','Czech Republic','0');");
E_D("replace into `ecs_cus_jy_country` values('63','204','贝宁','Benin','0');");
E_D("replace into `ecs_cus_jy_country` values('64','208','丹麦','Denmark','0');");
E_D("replace into `ecs_cus_jy_country` values('65','212','多米尼克','Dominica','0');");
E_D("replace into `ecs_cus_jy_country` values('66','214','多米尼加共和国','Dominican Republic','0');");
E_D("replace into `ecs_cus_jy_country` values('67','218','厄瓜多尔','Ecuador','0');");
E_D("replace into `ecs_cus_jy_country` values('68','222','萨尔瓦多','El Salvador','0');");
E_D("replace into `ecs_cus_jy_country` values('69','226','赤道几内亚','Equatorial Guinea','0');");
E_D("replace into `ecs_cus_jy_country` values('70','231','埃塞俄比亚','Ethiopia','0');");
E_D("replace into `ecs_cus_jy_country` values('71','232','厄立特里亚','Eritrea','0');");
E_D("replace into `ecs_cus_jy_country` values('72','233','爱沙尼亚','Estonia','0');");
E_D("replace into `ecs_cus_jy_country` values('73','234','法罗群岛','Faroe Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('74','238','马尔维纳斯群岛（福克兰群岛）','Malvinas Islands (Falkland Islands)','0');");
E_D("replace into `ecs_cus_jy_country` values('75','239','南乔治亚岛和南桑德韦奇岛','South Georgia and the South Sandwich Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('76','242','斐济','Fiji','0');");
E_D("replace into `ecs_cus_jy_country` values('77','246','芬兰','Finland','0');");
E_D("replace into `ecs_cus_jy_country` values('78','250','法国','France','0');");
E_D("replace into `ecs_cus_jy_country` values('79','254','法属圭亚那','French Guiana','0');");
E_D("replace into `ecs_cus_jy_country` values('80','258','法属波利尼西亚','French Polynesia','0');");
E_D("replace into `ecs_cus_jy_country` values('81','260','法属南部领土','French Southern Territories','0');");
E_D("replace into `ecs_cus_jy_country` values('82','262','吉布提','Djibouti','0');");
E_D("replace into `ecs_cus_jy_country` values('83','266','加蓬','Gabon','0');");
E_D("replace into `ecs_cus_jy_country` values('84','268','格鲁吉亚','Georgia','0');");
E_D("replace into `ecs_cus_jy_country` values('85','270','冈比亚','Gambia','0');");
E_D("replace into `ecs_cus_jy_country` values('86','276','德国','Germany','0');");
E_D("replace into `ecs_cus_jy_country` values('87','288','加纳','Ghana','0');");
E_D("replace into `ecs_cus_jy_country` values('88','292','直布罗陀','Gibraltar','0');");
E_D("replace into `ecs_cus_jy_country` values('89','296','基里巴斯','Kiribati','0');");
E_D("replace into `ecs_cus_jy_country` values('90','300','希腊','Greece','0');");
E_D("replace into `ecs_cus_jy_country` values('91','304','格陵兰','Greenland','0');");
E_D("replace into `ecs_cus_jy_country` values('92','308','格林纳达','Grenada','0');");
E_D("replace into `ecs_cus_jy_country` values('93','312','瓜德罗普','Guadeloupe','0');");
E_D("replace into `ecs_cus_jy_country` values('94','316','关岛','Guam','0');");
E_D("replace into `ecs_cus_jy_country` values('95','320','危地马拉','Guatemala','0');");
E_D("replace into `ecs_cus_jy_country` values('96','324','几内亚','Guinea','0');");
E_D("replace into `ecs_cus_jy_country` values('97','328','圭亚那','Guyana','0');");
E_D("replace into `ecs_cus_jy_country` values('98','332','海地','Haiti','0');");
E_D("replace into `ecs_cus_jy_country` values('99','334','赫德岛和麦克唐纳岛','Heard Island and Mc Donald Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('100','336','梵蒂冈','Vatican','0');");
E_D("replace into `ecs_cus_jy_country` values('101','340','洪都拉斯','Honduras','0');");
E_D("replace into `ecs_cus_jy_country` values('102','344','中国香港','Hong Kong(CHINA)','0');");
E_D("replace into `ecs_cus_jy_country` values('103','348','匈牙利','Hungary','0');");
E_D("replace into `ecs_cus_jy_country` values('104','352','冰岛','Iceland','0');");
E_D("replace into `ecs_cus_jy_country` values('105','356','印度','India','0');");
E_D("replace into `ecs_cus_jy_country` values('106','360','印度尼西亚','Indonesia','0');");
E_D("replace into `ecs_cus_jy_country` values('107','364','伊朗','Iran','0');");
E_D("replace into `ecs_cus_jy_country` values('108','368','伊拉克','Iraq','0');");
E_D("replace into `ecs_cus_jy_country` values('109','372','爱尔兰','Ireland','0');");
E_D("replace into `ecs_cus_jy_country` values('110','374','巴勒斯坦','Palestine','0');");
E_D("replace into `ecs_cus_jy_country` values('111','376','以色列','Israel','0');");
E_D("replace into `ecs_cus_jy_country` values('112','380','意大利','Italy','0');");
E_D("replace into `ecs_cus_jy_country` values('113','384','科特迪瓦','Cote d''Ivoire','0');");
E_D("replace into `ecs_cus_jy_country` values('114','388','牙买加','Jamaica','0');");
E_D("replace into `ecs_cus_jy_country` values('115','392','日本','Japan','0');");
E_D("replace into `ecs_cus_jy_country` values('116','398','哈萨克斯坦','Kazakhstan','0');");
E_D("replace into `ecs_cus_jy_country` values('117','400','约旦','Jordan','0');");
E_D("replace into `ecs_cus_jy_country` values('118','404','肯尼亚','Kenya','0');");
E_D("replace into `ecs_cus_jy_country` values('119','408','朝鲜','Korea, Democratic People''s Republic of','0');");
E_D("replace into `ecs_cus_jy_country` values('120','410','韩国','Korea, Republic of','0');");
E_D("replace into `ecs_cus_jy_country` values('121','414','科威特','Kuwait','0');");
E_D("replace into `ecs_cus_jy_country` values('122','417','吉尔吉斯斯坦','Kyrgyzstan','0');");
E_D("replace into `ecs_cus_jy_country` values('123','418','老挝','Laos','0');");
E_D("replace into `ecs_cus_jy_country` values('124','422','黎巴嫩','Lebanon','0');");
E_D("replace into `ecs_cus_jy_country` values('125','426','莱索托','Lesotho','0');");
E_D("replace into `ecs_cus_jy_country` values('126','428','拉脱维亚','Latvia','0');");
E_D("replace into `ecs_cus_jy_country` values('127','430','利比里亚','Liberia','0');");
E_D("replace into `ecs_cus_jy_country` values('128','434','利比亚','Libya','0');");
E_D("replace into `ecs_cus_jy_country` values('129','438','列支敦士登','Liechtenstein','0');");
E_D("replace into `ecs_cus_jy_country` values('130','440','立陶宛','Lithuania','0');");
E_D("replace into `ecs_cus_jy_country` values('131','442','卢森堡','Luxembourg','0');");
E_D("replace into `ecs_cus_jy_country` values('132','446','中国澳门','Macau(CHINA)','0');");
E_D("replace into `ecs_cus_jy_country` values('133','450','马达加斯加','Madagascar','0');");
E_D("replace into `ecs_cus_jy_country` values('134','454','马拉维','Malawi','0');");
E_D("replace into `ecs_cus_jy_country` values('135','458','马来西亚','Malaysia','0');");
E_D("replace into `ecs_cus_jy_country` values('136','462','马尔代夫','Maldives','0');");
E_D("replace into `ecs_cus_jy_country` values('137','466','马里','Mali','0');");
E_D("replace into `ecs_cus_jy_country` values('138','470','马耳他','Malta','0');");
E_D("replace into `ecs_cus_jy_country` values('139','474','马提尼克','Martinique','0');");
E_D("replace into `ecs_cus_jy_country` values('140','478','毛里塔尼亚','Mauritania','0');");
E_D("replace into `ecs_cus_jy_country` values('141','480','毛里求斯','Mauritius','0');");
E_D("replace into `ecs_cus_jy_country` values('142','482','梅利利亚','Melilla','0');");
E_D("replace into `ecs_cus_jy_country` values('143','484','墨西哥','Mexico','0');");
E_D("replace into `ecs_cus_jy_country` values('144','492','摩纳哥','Monaco','0');");
E_D("replace into `ecs_cus_jy_country` values('145','496','蒙古','Mongolia','0');");
E_D("replace into `ecs_cus_jy_country` values('146','498','摩尔多瓦','Moldova','0');");
E_D("replace into `ecs_cus_jy_country` values('147','499','黑山共和国','Republic of Montenegro','0');");
E_D("replace into `ecs_cus_jy_country` values('148','500','蒙特塞拉特','Montserrat','0');");
E_D("replace into `ecs_cus_jy_country` values('149','504','摩洛哥','Morocco','0');");
E_D("replace into `ecs_cus_jy_country` values('150','508','莫桑比克','Mozambique','0');");
E_D("replace into `ecs_cus_jy_country` values('151','512','阿曼','Oman','0');");
E_D("replace into `ecs_cus_jy_country` values('152','516','纳米比亚','Namibia','0');");
E_D("replace into `ecs_cus_jy_country` values('153','520','瑙鲁','Nauru','0');");
E_D("replace into `ecs_cus_jy_country` values('154','524','尼泊尔','Nepal','0');");
E_D("replace into `ecs_cus_jy_country` values('155','528','荷兰','Nether lands','0');");
E_D("replace into `ecs_cus_jy_country` values('156','530','荷属安的列斯','Netherlands Antilles','0');");
E_D("replace into `ecs_cus_jy_country` values('157','533','阿鲁巴','Aruba','0');");
E_D("replace into `ecs_cus_jy_country` values('158','540','新喀里多尼亚','New Caledonia','0');");
E_D("replace into `ecs_cus_jy_country` values('159','548','瓦努阿图','Vanuatu','0');");
E_D("replace into `ecs_cus_jy_country` values('160','554','新西兰','New Zealand','0');");
E_D("replace into `ecs_cus_jy_country` values('161','558','尼加拉瓜','Nicaragua','0');");
E_D("replace into `ecs_cus_jy_country` values('162','562','尼日尔','Niger','0');");
E_D("replace into `ecs_cus_jy_country` values('163','566','尼日利亚','Nigeria','0');");
E_D("replace into `ecs_cus_jy_country` values('164','570','纽埃','Niue','0');");
E_D("replace into `ecs_cus_jy_country` values('165','574','诺福克岛','Norfolk Island','0');");
E_D("replace into `ecs_cus_jy_country` values('166','578','挪威','Norway','0');");
E_D("replace into `ecs_cus_jy_country` values('167','580','北马里亚纳自由联邦','Northern Mariana Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('168','581','美属太平洋各群岛','United States Miscellaneous Pacific Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('169','582','太平洋群岛','Pacific Islands(trust territory)','0');");
E_D("replace into `ecs_cus_jy_country` values('170','583','密克罗尼西亚','Micronesia','0');");
E_D("replace into `ecs_cus_jy_country` values('171','584','马绍尔群岛','Marshall Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('172','585','帕劳','Palau','0');");
E_D("replace into `ecs_cus_jy_country` values('173','586','巴基斯坦','Pakistan','0');");
E_D("replace into `ecs_cus_jy_country` values('174','591','巴拿马','Panama','0');");
E_D("replace into `ecs_cus_jy_country` values('175','598','巴布亚新几内亚','Papua New Guinea','0');");
E_D("replace into `ecs_cus_jy_country` values('176','600','巴拉圭','Paraguay','0');");
E_D("replace into `ecs_cus_jy_country` values('177','604','秘鲁','Peru','0');");
E_D("replace into `ecs_cus_jy_country` values('178','608','菲律宾','Philippines','0');");
E_D("replace into `ecs_cus_jy_country` values('179','612','皮特凯恩群岛','Pitcairn Islands Group','0');");
E_D("replace into `ecs_cus_jy_country` values('180','616','波兰','Poland','0');");
E_D("replace into `ecs_cus_jy_country` values('181','620','葡萄牙','Portugal','0');");
E_D("replace into `ecs_cus_jy_country` values('182','624','几内亚比绍','Guine-bissau','0');");
E_D("replace into `ecs_cus_jy_country` values('183','626','东帝汶','East Timor','0');");
E_D("replace into `ecs_cus_jy_country` values('184','630','波多黎各','Puerto Rico','0');");
E_D("replace into `ecs_cus_jy_country` values('185','634','卡塔尔','Qatar','0');");
E_D("replace into `ecs_cus_jy_country` values('186','638','留尼汪','Reunion','0');");
E_D("replace into `ecs_cus_jy_country` values('187','642','罗马尼亚','Romania','0');");
E_D("replace into `ecs_cus_jy_country` values('188','643','俄罗斯','Russia','0');");
E_D("replace into `ecs_cus_jy_country` values('189','646','卢旺达','Rwanda','0');");
E_D("replace into `ecs_cus_jy_country` values('190','654','圣赫勒拿','Saint Helena','0');");
E_D("replace into `ecs_cus_jy_country` values('191','659','圣基茨和尼维斯','Saint Kitts and Nevis','0');");
E_D("replace into `ecs_cus_jy_country` values('192','660','安圭拉','Anguilla','0');");
E_D("replace into `ecs_cus_jy_country` values('193','662','圣卢西亚','Saint Lucia','0');");
E_D("replace into `ecs_cus_jy_country` values('194','666','圣皮埃尔和密克隆','Saint Pierre and Miquelon','0');");
E_D("replace into `ecs_cus_jy_country` values('195','670','圣文森特和格林纳丁斯','Saint Vincent and the Grenadines','0');");
E_D("replace into `ecs_cus_jy_country` values('196','674','圣马力诺','San Marino','0');");
E_D("replace into `ecs_cus_jy_country` values('197','678','圣多美和普林西比','Sao Tome and Principe','0');");
E_D("replace into `ecs_cus_jy_country` values('198','682','沙特阿拉伯','Saudi Arabia','0');");
E_D("replace into `ecs_cus_jy_country` values('199','686','塞内加尔','Senegal','0');");
E_D("replace into `ecs_cus_jy_country` values('200','688','塞尔维亚共和国','Republic of Serbia','0');");
E_D("replace into `ecs_cus_jy_country` values('201','690','塞舌尔','Seychelles','0');");
E_D("replace into `ecs_cus_jy_country` values('202','694','塞拉利昂','Sierra Leone','0');");
E_D("replace into `ecs_cus_jy_country` values('203','702','新加坡','Singapore','0');");
E_D("replace into `ecs_cus_jy_country` values('204','703','斯洛伐克','Slovakia','0');");
E_D("replace into `ecs_cus_jy_country` values('205','704','越南','Viet Nam','0');");
E_D("replace into `ecs_cus_jy_country` values('206','705','斯洛文尼亚','Slovenia','0');");
E_D("replace into `ecs_cus_jy_country` values('207','706','索马里','Somalia','0');");
E_D("replace into `ecs_cus_jy_country` values('208','710','南非','South Africa','0');");
E_D("replace into `ecs_cus_jy_country` values('209','716','津巴布韦','Zimbabwe','0');");
E_D("replace into `ecs_cus_jy_country` values('210','724','西班牙','Spain','0');");
E_D("replace into `ecs_cus_jy_country` values('211','732','西撒哈拉','Western Sahara','0');");
E_D("replace into `ecs_cus_jy_country` values('212','736','苏丹(作废)','Sudan','0');");
E_D("replace into `ecs_cus_jy_country` values('213','740','苏里南','Suriname','0');");
E_D("replace into `ecs_cus_jy_country` values('214','744','斯瓦巴德群岛','Svalbard and Jan Mayen Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('215','748','斯威士兰','Swaziland','0');");
E_D("replace into `ecs_cus_jy_country` values('216','752','瑞典','Sweden','0');");
E_D("replace into `ecs_cus_jy_country` values('217','756','瑞士','Switzerland','0');");
E_D("replace into `ecs_cus_jy_country` values('218','760','叙利亚','Syria','0');");
E_D("replace into `ecs_cus_jy_country` values('219','762','塔吉克斯坦','Tajikistan','0');");
E_D("replace into `ecs_cus_jy_country` values('220','764','泰国','Thailand','0');");
E_D("replace into `ecs_cus_jy_country` values('221','768','多哥','Togo','0');");
E_D("replace into `ecs_cus_jy_country` values('222','772','托克劳','Tokelau','0');");
E_D("replace into `ecs_cus_jy_country` values('223','776','汤加','Tonga','0');");
E_D("replace into `ecs_cus_jy_country` values('224','780','特立尼达和多巴哥','Trinidad and Tobago','0');");
E_D("replace into `ecs_cus_jy_country` values('225','784','阿联酋','United Arab Emirates','0');");
E_D("replace into `ecs_cus_jy_country` values('226','788','突尼斯','Tunisia','0');");
E_D("replace into `ecs_cus_jy_country` values('227','792','土耳其','Turkey','0');");
E_D("replace into `ecs_cus_jy_country` values('228','795','土库曼斯坦','Turkmenistan','0');");
E_D("replace into `ecs_cus_jy_country` values('229','796','特克斯和凯科斯群岛','Turks and Caicos Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('230','798','图瓦卢','Tuvalu','0');");
E_D("replace into `ecs_cus_jy_country` values('231','800','乌干达','Uganda','0');");
E_D("replace into `ecs_cus_jy_country` values('232','804','乌克兰','Ukraine','0');");
E_D("replace into `ecs_cus_jy_country` values('233','807','马其顿','Macedonia','0');");
E_D("replace into `ecs_cus_jy_country` values('234','818','埃及','Egypt','0');");
E_D("replace into `ecs_cus_jy_country` values('235','826','英国','United Kingdom','0');");
E_D("replace into `ecs_cus_jy_country` values('236','834','坦桑尼亚','Tanzania','0');");
E_D("replace into `ecs_cus_jy_country` values('237','840','美国','United States','0');");
E_D("replace into `ecs_cus_jy_country` values('238','850','美属维尔京群岛','United States Virgin Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('239','854','布基纳法索','Burkina Faso','0');");
E_D("replace into `ecs_cus_jy_country` values('240','858','乌拉圭','Uruguay','0');");
E_D("replace into `ecs_cus_jy_country` values('241','860','乌兹别克斯坦','Uzbekistan','0');");
E_D("replace into `ecs_cus_jy_country` values('242','862','委内瑞拉','Venezuela','0');");
E_D("replace into `ecs_cus_jy_country` values('243','872','威克岛','Wake Island','0');");
E_D("replace into `ecs_cus_jy_country` values('244','876','瓦利斯和富图纳群岛','Wallis and Futuna Islands','0');");
E_D("replace into `ecs_cus_jy_country` values('245','882','萨摩亚','The Independent State of Samoa','0');");
E_D("replace into `ecs_cus_jy_country` values('246','887','也门','Yemen','0');");
E_D("replace into `ecs_cus_jy_country` values('247','894','赞比亚','Zambia','0');");
E_D("replace into `ecs_cus_jy_country` values('248','903','亚洲','Asia','0');");
E_D("replace into `ecs_cus_jy_country` values('249','906','非洲','Africa','0');");
E_D("replace into `ecs_cus_jy_country` values('250','909','欧洲','Europe','0');");
E_D("replace into `ecs_cus_jy_country` values('251','910','欧盟','Europe Union','0');");
E_D("replace into `ecs_cus_jy_country` values('252','912','南美洲','South America','0');");
E_D("replace into `ecs_cus_jy_country` values('253','915','北美洲','North America','0');");
E_D("replace into `ecs_cus_jy_country` values('254','918','大洋洲','Oceania','0');");
E_D("replace into `ecs_cus_jy_country` values('255','991','保税区','','0');");
E_D("replace into `ecs_cus_jy_country` values('256','992','出口加工区','Export Processing Zone','0');");
E_D("replace into `ecs_cus_jy_country` values('257','999','未列出的国家或地区','Unlisted Countries or Districts','0');");
E_D("replace into `ecs_cus_jy_country` values('258','901','圣马丁岛','Saint Martin','0');");

require("../../inc/footer.php");
?>