<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `ecs_cus_hg_country`;");
E_C("CREATE TABLE `ecs_cus_hg_country` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `country_code` varchar(10) DEFAULT NULL,
  `iso_e` varchar(10) DEFAULT NULL,
  `coun_c_name` varchar(40) DEFAULT NULL,
  `coun_e_name` varchar(60) DEFAULT NULL,
  `def` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `country_code` (`country_code`)
) ENGINE=MyISAM AUTO_INCREMENT=246 DEFAULT CHARSET=utf8");
E_D("replace into `ecs_cus_hg_country` values('1','101','AFG','阿富汗','Afghanistan','0');");
E_D("replace into `ecs_cus_hg_country` values('2','102','BHR','巴林','Bahrian','0');");
E_D("replace into `ecs_cus_hg_country` values('3','103','BGD','孟加拉国','Bangladesh','0');");
E_D("replace into `ecs_cus_hg_country` values('4','104','BTN','不丹','Bhutan','0');");
E_D("replace into `ecs_cus_hg_country` values('5','105','BRN','文莱','Brunei','0');");
E_D("replace into `ecs_cus_hg_country` values('6','106','MMR','缅甸','Myanmar','0');");
E_D("replace into `ecs_cus_hg_country` values('7','107','KHM','柬埔寨','Cambodia','0');");
E_D("replace into `ecs_cus_hg_country` values('8','108','CYP','塞浦路斯','Cyprus','0');");
E_D("replace into `ecs_cus_hg_country` values('9','109','PRK','朝鲜','Korea,DPR','0');");
E_D("replace into `ecs_cus_hg_country` values('10','110','HKG','香港','Hong Kong','0');");
E_D("replace into `ecs_cus_hg_country` values('11','111','IND','印度','India','0');");
E_D("replace into `ecs_cus_hg_country` values('12','112','IDN','印度尼西亚','Indonesia','0');");
E_D("replace into `ecs_cus_hg_country` values('13','113','IRN','伊朗','Iran','0');");
E_D("replace into `ecs_cus_hg_country` values('14','114','IRQ','伊拉克','Iraq','0');");
E_D("replace into `ecs_cus_hg_country` values('15','115','ISR','以色列','Israel','0');");
E_D("replace into `ecs_cus_hg_country` values('16','116','JPN','日本','Japan','0');");
E_D("replace into `ecs_cus_hg_country` values('17','117','JOR','约旦','Jordan','0');");
E_D("replace into `ecs_cus_hg_country` values('18','118','KWT','科威特','Kuwait','0');");
E_D("replace into `ecs_cus_hg_country` values('19','119','LAO','老挝','Lao PDR','0');");
E_D("replace into `ecs_cus_hg_country` values('20','120','LBN','黎巴嫩','Lebanon','0');");
E_D("replace into `ecs_cus_hg_country` values('21','121','MAC','澳门','Macau','0');");
E_D("replace into `ecs_cus_hg_country` values('22','122','MYS','马来西亚','Malaysia','0');");
E_D("replace into `ecs_cus_hg_country` values('23','123','MDV','马尔代夫','Maldives','0');");
E_D("replace into `ecs_cus_hg_country` values('24','124','MNG','蒙古','Mongolia','0');");
E_D("replace into `ecs_cus_hg_country` values('25','125','NPL','尼泊尔联邦民主共和国','Nepal, FDR','0');");
E_D("replace into `ecs_cus_hg_country` values('26','126','OMN','阿曼','Oman','0');");
E_D("replace into `ecs_cus_hg_country` values('27','127','PAK','巴基斯坦','Pakistan','0');");
E_D("replace into `ecs_cus_hg_country` values('28','128','PSE','巴勒斯坦','Palestine','0');");
E_D("replace into `ecs_cus_hg_country` values('29','129','PHL','菲律宾','Philippines','0');");
E_D("replace into `ecs_cus_hg_country` values('30','130','QAT','卡塔尔','Qatar','0');");
E_D("replace into `ecs_cus_hg_country` values('31','131','SAU','沙特阿拉伯','Saudi Arabia','0');");
E_D("replace into `ecs_cus_hg_country` values('32','132','SGP','新加坡','Singapore','0');");
E_D("replace into `ecs_cus_hg_country` values('33','133','KOR','韩国','Korea, Rep.','0');");
E_D("replace into `ecs_cus_hg_country` values('34','134','LKA','斯里兰卡','Sri Lanka','0');");
E_D("replace into `ecs_cus_hg_country` values('35','135','SYR','叙利亚','Syrian Arab Republic','0');");
E_D("replace into `ecs_cus_hg_country` values('36','136','THA','泰国','Thailand','0');");
E_D("replace into `ecs_cus_hg_country` values('37','137','TUR','土耳其','Turkey','0');");
E_D("replace into `ecs_cus_hg_country` values('38','138','ARE','阿联酋','United Arab Emirates','0');");
E_D("replace into `ecs_cus_hg_country` values('39','139','YEM','也门','Yemen','0');");
E_D("replace into `ecs_cus_hg_country` values('40','141','NVM','越南','Viet Nam','0');");
E_D("replace into `ecs_cus_hg_country` values('41','142','CHN','中国','China','1');");
E_D("replace into `ecs_cus_hg_country` values('42','143','TWN','台澎金马关税区','Taiwan, Prov.of China','0');");
E_D("replace into `ecs_cus_hg_country` values('43','144','TLS','东帝汶','Timor-Leste','0');");
E_D("replace into `ecs_cus_hg_country` values('44','145','KAZ','哈萨克斯坦','Kazakhstan','0');");
E_D("replace into `ecs_cus_hg_country` values('45','146','KGZ','吉尔吉斯斯坦','Kyrgyzstan','0');");
E_D("replace into `ecs_cus_hg_country` values('46','147','TJK','塔吉克斯坦','Tajikistan','0');");
E_D("replace into `ecs_cus_hg_country` values('47','148','TKM','土库曼斯坦','Turkmenistan','0');");
E_D("replace into `ecs_cus_hg_country` values('48','149','UZB','乌兹别克斯坦','Uzbekistan','0');");
E_D("replace into `ecs_cus_hg_country` values('49','199','','亚洲其他国家(地区)','Oth. Asia nes','0');");
E_D("replace into `ecs_cus_hg_country` values('50','201','DZA','阿尔及利亚','Algeria','0');");
E_D("replace into `ecs_cus_hg_country` values('51','202','AGO','安哥拉','Angola','0');");
E_D("replace into `ecs_cus_hg_country` values('52','203','BEN','贝宁','Benin','0');");
E_D("replace into `ecs_cus_hg_country` values('53','204','BWA','博茨瓦纳','Botswana','0');");
E_D("replace into `ecs_cus_hg_country` values('54','205','BDI','布隆迪','Burundi','0');");
E_D("replace into `ecs_cus_hg_country` values('55','206','CMR','喀麦隆','Cameroon','0');");
E_D("replace into `ecs_cus_hg_country` values('56','207','','加那利群岛','Canary Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('57','208','CPV','佛得角','Cape Verde','0');");
E_D("replace into `ecs_cus_hg_country` values('58','209','CAF','中非','Central African Republic.','0');");
E_D("replace into `ecs_cus_hg_country` values('59','210','','塞卜泰(休达)','Ceuta','0');");
E_D("replace into `ecs_cus_hg_country` values('60','211','TCD','乍得','Chad','0');");
E_D("replace into `ecs_cus_hg_country` values('61','212','COM','科摩罗','Comoros','0');");
E_D("replace into `ecs_cus_hg_country` values('62','213','COG','刚果(布)','Congo','0');");
E_D("replace into `ecs_cus_hg_country` values('63','214','DJI','吉布提','Djibouti','0');");
E_D("replace into `ecs_cus_hg_country` values('64','215','EGY','埃及','Egypt','0');");
E_D("replace into `ecs_cus_hg_country` values('65','216','GNQ','赤道几内亚','Equatorial Guinea','0');");
E_D("replace into `ecs_cus_hg_country` values('66','217','ETH','埃塞俄比亚','Ethiopia','0');");
E_D("replace into `ecs_cus_hg_country` values('67','218','GAB','加蓬','Gabon','0');");
E_D("replace into `ecs_cus_hg_country` values('68','219','GMB','冈比亚','Gambia','0');");
E_D("replace into `ecs_cus_hg_country` values('69','220','GHA','加纳','Ghana','0');");
E_D("replace into `ecs_cus_hg_country` values('70','221','GIN','几内亚','Guinea','0');");
E_D("replace into `ecs_cus_hg_country` values('71','222','GNB','几内亚比绍','Guinea-Bissau','0');");
E_D("replace into `ecs_cus_hg_country` values('72','223','CIV','科特迪瓦','Cote d''lvoire','0');");
E_D("replace into `ecs_cus_hg_country` values('73','224','KEN','肯尼亚','Kenya','0');");
E_D("replace into `ecs_cus_hg_country` values('74','225','LBR','利比里亚','Liberia','0');");
E_D("replace into `ecs_cus_hg_country` values('75','226','LBY','利比亚','Libyan Arab Jamahiriya','0');");
E_D("replace into `ecs_cus_hg_country` values('76','227','MDG','马达加斯加','Madagascar','0');");
E_D("replace into `ecs_cus_hg_country` values('77','228','MWI','马拉维','Malawi','0');");
E_D("replace into `ecs_cus_hg_country` values('78','229','MLI','马里','Mali','0');");
E_D("replace into `ecs_cus_hg_country` values('79','230','MRT','毛里塔尼亚','Mauritania','0');");
E_D("replace into `ecs_cus_hg_country` values('80','231','MUS','毛里求斯','Mauritius','0');");
E_D("replace into `ecs_cus_hg_country` values('81','232','MAR','摩洛哥','Morocco','0');");
E_D("replace into `ecs_cus_hg_country` values('82','233','MOZ','莫桑比克','Mozambique','0');");
E_D("replace into `ecs_cus_hg_country` values('83','234','NAM','纳米比亚','Namibia','0');");
E_D("replace into `ecs_cus_hg_country` values('84','235','NER','尼日尔','Niger','0');");
E_D("replace into `ecs_cus_hg_country` values('85','236','NGA','尼日利亚','Nigeria','0');");
E_D("replace into `ecs_cus_hg_country` values('86','237','REU','留尼汪','Reunion','0');");
E_D("replace into `ecs_cus_hg_country` values('87','238','RWA','卢旺达','Rwanda','0');");
E_D("replace into `ecs_cus_hg_country` values('88','239','STP','圣多美和普林西比','Sao Tome and Principe','0');");
E_D("replace into `ecs_cus_hg_country` values('89','240','SEN','塞内加尔','Senegal','0');");
E_D("replace into `ecs_cus_hg_country` values('90','241','SYC','塞舌尔','Seychelles','0');");
E_D("replace into `ecs_cus_hg_country` values('91','242','SLE','塞拉利昂','Sierra Leone','0');");
E_D("replace into `ecs_cus_hg_country` values('92','243','SOM','索马里','Somalia','0');");
E_D("replace into `ecs_cus_hg_country` values('93','244','ZAF','南非','South Africa','0');");
E_D("replace into `ecs_cus_hg_country` values('94','245','ESH','西撒哈拉','Western Sahara','0');");
E_D("replace into `ecs_cus_hg_country` values('95','246','SDN','苏丹','Sudan','0');");
E_D("replace into `ecs_cus_hg_country` values('96','247','TZA','坦桑尼亚','Tanzania','0');");
E_D("replace into `ecs_cus_hg_country` values('97','248','TGO','多哥','Togo','0');");
E_D("replace into `ecs_cus_hg_country` values('98','249','TUN','突尼斯','Tunisia','0');");
E_D("replace into `ecs_cus_hg_country` values('99','250','UGA','乌干达','Uganda','0');");
E_D("replace into `ecs_cus_hg_country` values('100','251','BFA','布基纳法索','Burkina Faso','0');");
E_D("replace into `ecs_cus_hg_country` values('101','252','COD','刚果(金)','Congo,DR','0');");
E_D("replace into `ecs_cus_hg_country` values('102','253','ZMB','赞比亚','Zambia','0');");
E_D("replace into `ecs_cus_hg_country` values('103','254','ZWE','津巴布韦','Zimbabwe','0');");
E_D("replace into `ecs_cus_hg_country` values('104','255','LSO','莱索托','Lesotho','0');");
E_D("replace into `ecs_cus_hg_country` values('105','256','','梅利利亚','Melilla','0');");
E_D("replace into `ecs_cus_hg_country` values('106','257','SWZ','斯威士兰','Swaziland','0');");
E_D("replace into `ecs_cus_hg_country` values('107','258','ERI','厄立特里亚','Eritrea','0');");
E_D("replace into `ecs_cus_hg_country` values('108','259','MYT','马约特','Mayotte','0');");
E_D("replace into `ecs_cus_hg_country` values('109','260','','南苏丹共和国','Republic of South Sudan ','0');");
E_D("replace into `ecs_cus_hg_country` values('110','299','','非洲其他国家(地区)','Oth. Afr. nes','0');");
E_D("replace into `ecs_cus_hg_country` values('111','301','BEL','比利时','Belgium','0');");
E_D("replace into `ecs_cus_hg_country` values('112','302','DNK','丹麦','Denmark','0');");
E_D("replace into `ecs_cus_hg_country` values('113','303','GBR','英国','United Kingdom','0');");
E_D("replace into `ecs_cus_hg_country` values('114','304','DEU','德国','Germany','0');");
E_D("replace into `ecs_cus_hg_country` values('115','305','FRA','法国','France','0');");
E_D("replace into `ecs_cus_hg_country` values('116','306','IRL','爱尔兰','Ireland','0');");
E_D("replace into `ecs_cus_hg_country` values('117','307','ITA','意大利','Italy','0');");
E_D("replace into `ecs_cus_hg_country` values('118','308','LUX','卢森堡','Luxembourg','0');");
E_D("replace into `ecs_cus_hg_country` values('119','309','NLD','荷兰','Netherlands','0');");
E_D("replace into `ecs_cus_hg_country` values('120','310','GRC','希腊','Greece','0');");
E_D("replace into `ecs_cus_hg_country` values('121','311','PRT','葡萄牙','Portugal','0');");
E_D("replace into `ecs_cus_hg_country` values('122','312','ESP','西班牙','Spain','0');");
E_D("replace into `ecs_cus_hg_country` values('123','313','ALB','阿尔巴尼亚','Albania','0');");
E_D("replace into `ecs_cus_hg_country` values('124','314','AND','安道尔','Andorra','0');");
E_D("replace into `ecs_cus_hg_country` values('125','315','AUT','奥地利','Austria','0');");
E_D("replace into `ecs_cus_hg_country` values('126','316','BGR','保加利亚','Bulgaria','0');");
E_D("replace into `ecs_cus_hg_country` values('127','318','FIN','芬兰','Finland','0');");
E_D("replace into `ecs_cus_hg_country` values('128','320','GIB','直布罗陀','Gibraltar','0');");
E_D("replace into `ecs_cus_hg_country` values('129','321','HUN','匈牙利','Hungary','0');");
E_D("replace into `ecs_cus_hg_country` values('130','322','ISL','冰岛','Iceland','0');");
E_D("replace into `ecs_cus_hg_country` values('131','323','LIE','列支敦士登','Liechtenstein','0');");
E_D("replace into `ecs_cus_hg_country` values('132','324','MLT','马耳他','Malta','0');");
E_D("replace into `ecs_cus_hg_country` values('133','325','MCO','摩纳哥','Monaco','0');");
E_D("replace into `ecs_cus_hg_country` values('134','326','NOR','挪威','Norway','0');");
E_D("replace into `ecs_cus_hg_country` values('135','327','POL','波兰','Poland','0');");
E_D("replace into `ecs_cus_hg_country` values('136','328','ROM','罗马尼亚','Romania','0');");
E_D("replace into `ecs_cus_hg_country` values('137','329','SMR','圣马力诺','San Marino','0');");
E_D("replace into `ecs_cus_hg_country` values('138','330','SWE','瑞典','Sweden','0');");
E_D("replace into `ecs_cus_hg_country` values('139','331','CHE','瑞士','Switzerland','0');");
E_D("replace into `ecs_cus_hg_country` values('140','334','EST','爱沙尼亚','Estonia','0');");
E_D("replace into `ecs_cus_hg_country` values('141','335','LVA','拉脱维亚','Latvia','0');");
E_D("replace into `ecs_cus_hg_country` values('142','336','LTU','立陶宛','Lithuania','0');");
E_D("replace into `ecs_cus_hg_country` values('143','337','GEO','格鲁吉亚','Georgia','0');");
E_D("replace into `ecs_cus_hg_country` values('144','338','ARM','亚美尼亚','Armenia','0');");
E_D("replace into `ecs_cus_hg_country` values('145','339','AZE','阿塞拜疆','Azerbai jan','0');");
E_D("replace into `ecs_cus_hg_country` values('146','340','BLR','白俄罗斯','Belarus','0');");
E_D("replace into `ecs_cus_hg_country` values('147','343','MDA','摩尔多瓦','Moldova','0');");
E_D("replace into `ecs_cus_hg_country` values('148','344','RUS','俄罗斯联邦','Russian Federation','0');");
E_D("replace into `ecs_cus_hg_country` values('149','347','UKR','乌克兰','Ukraine','0');");
E_D("replace into `ecs_cus_hg_country` values('150','349','','塞尔维亚和黑山','','0');");
E_D("replace into `ecs_cus_hg_country` values('151','350','SVN','斯洛文尼亚','Slovenia ','0');");
E_D("replace into `ecs_cus_hg_country` values('152','351','HRV','克罗地亚','Croatia','0');");
E_D("replace into `ecs_cus_hg_country` values('153','352','CZE','捷克','Czech Republic','0');");
E_D("replace into `ecs_cus_hg_country` values('154','353','SVK','斯洛伐克','Slovakia','0');");
E_D("replace into `ecs_cus_hg_country` values('155','354','MKD','前南马其顿','Macedonia,FYR','0');");
E_D("replace into `ecs_cus_hg_country` values('156','355','BIH','波黑','Bosnia and Hercegovina','0');");
E_D("replace into `ecs_cus_hg_country` values('157','356','VAT','梵蒂冈城国','Vatican City State','0');");
E_D("replace into `ecs_cus_hg_country` values('158','357','FRO','法罗群岛','Faroe Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('159','358','SRB','塞尔维亚','Serbia','0');");
E_D("replace into `ecs_cus_hg_country` values('160','359','MNE','黑山','Montenegro','0');");
E_D("replace into `ecs_cus_hg_country` values('161','399','','欧洲其他国家(地区)','Oth. Eur. nes','0');");
E_D("replace into `ecs_cus_hg_country` values('162','401','ATG','安提瓜和巴布达','Antigua & Barbuda','0');");
E_D("replace into `ecs_cus_hg_country` values('163','402','ARG','阿根廷','Argentina','0');");
E_D("replace into `ecs_cus_hg_country` values('164','403','ABW','阿鲁巴','Aruba','0');");
E_D("replace into `ecs_cus_hg_country` values('165','404','BHS','巴哈马','Bahamas','0');");
E_D("replace into `ecs_cus_hg_country` values('166','405','BRB','巴巴多斯','Barbados','0');");
E_D("replace into `ecs_cus_hg_country` values('167','406','BLZ','伯利兹','Belize','0');");
E_D("replace into `ecs_cus_hg_country` values('168','408','BOL','多民族玻利维亚国','Estado Plurinacional de Bolivia','0');");
E_D("replace into `ecs_cus_hg_country` values('169','409','','博内尔','Bonaire','0');");
E_D("replace into `ecs_cus_hg_country` values('170','410','BRA','巴西','Brazil','0');");
E_D("replace into `ecs_cus_hg_country` values('171','411','CYM','开曼群岛','Cayman Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('172','412','CHL','智利','Chile','0');");
E_D("replace into `ecs_cus_hg_country` values('173','413','COL','哥伦比亚','Colombia','0');");
E_D("replace into `ecs_cus_hg_country` values('174','414','DMA','多米尼克','Dominica','0');");
E_D("replace into `ecs_cus_hg_country` values('175','415','CRI','哥斯达黎加','Costa Rica','0');");
E_D("replace into `ecs_cus_hg_country` values('176','416','CUB','古巴','Cuba','0');");
E_D("replace into `ecs_cus_hg_country` values('177','417','','库腊索岛','Curacao','0');");
E_D("replace into `ecs_cus_hg_country` values('178','418','DOM','多米尼加共和国','Dominican Republic','0');");
E_D("replace into `ecs_cus_hg_country` values('179','419','ECU','厄瓜多尔','Ecuador','0');");
E_D("replace into `ecs_cus_hg_country` values('180','420','GUF','法属圭亚那','French Guiana','0');");
E_D("replace into `ecs_cus_hg_country` values('181','421','GRD','格林纳达','Grenada','0');");
E_D("replace into `ecs_cus_hg_country` values('182','422','GLP','瓜德罗普','Guadeloupe','0');");
E_D("replace into `ecs_cus_hg_country` values('183','423','GTM','危地马拉','Guatemala','0');");
E_D("replace into `ecs_cus_hg_country` values('184','424','GUY','圭亚那','Guyana','0');");
E_D("replace into `ecs_cus_hg_country` values('185','425','HTI','海地','Haiti','0');");
E_D("replace into `ecs_cus_hg_country` values('186','426','HND','洪都拉斯','Honduras','0');");
E_D("replace into `ecs_cus_hg_country` values('187','427','JAM','牙买加','Jamaica','0');");
E_D("replace into `ecs_cus_hg_country` values('188','428','MTQ','马提尼克','Martinique','0');");
E_D("replace into `ecs_cus_hg_country` values('189','429','MEX','墨西哥','Mexico','0');");
E_D("replace into `ecs_cus_hg_country` values('190','430','MSR','蒙特塞拉特','Montserrat','0');");
E_D("replace into `ecs_cus_hg_country` values('191','431','NIC','尼加拉瓜','Nicaragua','0');");
E_D("replace into `ecs_cus_hg_country` values('192','432','PAN','巴拿马','Panama','0');");
E_D("replace into `ecs_cus_hg_country` values('193','433','PRY','巴拉圭','Paraguay','0');");
E_D("replace into `ecs_cus_hg_country` values('194','434','PER','秘鲁','Peru','0');");
E_D("replace into `ecs_cus_hg_country` values('195','435','PRI','波多黎各','Puerto Rico','0');");
E_D("replace into `ecs_cus_hg_country` values('196','436','','萨巴','Saba','0');");
E_D("replace into `ecs_cus_hg_country` values('197','437','LCA','圣卢西亚','Saint Lucia','0');");
E_D("replace into `ecs_cus_hg_country` values('198','438','','圣马丁岛','Saint Martin Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('199','439','VCT','圣文森特和格林纳丁斯','Saint Vincent and Grenadines','0');");
E_D("replace into `ecs_cus_hg_country` values('200','440','SLV','萨尔瓦多','El Salvador','0');");
E_D("replace into `ecs_cus_hg_country` values('201','441','SUR','苏里南','Suriname','0');");
E_D("replace into `ecs_cus_hg_country` values('202','442','TTO','特立尼达和多巴哥','Trinidad and Tobago','0');");
E_D("replace into `ecs_cus_hg_country` values('203','443','TCA','特克斯和凯科斯群岛','Turks and Caicos Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('204','444','URY','乌拉圭','Uruguay','0');");
E_D("replace into `ecs_cus_hg_country` values('205','445','VEN','委内瑞拉','Venezuela','0');");
E_D("replace into `ecs_cus_hg_country` values('206','446','VGB','英属维尔京群岛','Virgin  Islands, British','0');");
E_D("replace into `ecs_cus_hg_country` values('207','447','KNA','圣其茨和尼维斯','Saint  Kitts and Nevis','0');");
E_D("replace into `ecs_cus_hg_country` values('208','448','SPM','圣皮埃尔和密克隆','Saint.Pierre and Miquelon','0');");
E_D("replace into `ecs_cus_hg_country` values('209','449','ANT','荷属安地列斯','Netherlands Antilles','0');");
E_D("replace into `ecs_cus_hg_country` values('210','499','','拉丁美洲其他国家(地区)','Oth. L.Amer. nes','0');");
E_D("replace into `ecs_cus_hg_country` values('211','501','CAN','加拿大','Canada','0');");
E_D("replace into `ecs_cus_hg_country` values('212','502','USA','美国','United States','0');");
E_D("replace into `ecs_cus_hg_country` values('213','503','GRL','格陵兰','Greenland','0');");
E_D("replace into `ecs_cus_hg_country` values('214','504','BMU','百慕大','Bermuda','0');");
E_D("replace into `ecs_cus_hg_country` values('215','599','','北美洲其他国家(地区)','Oth. N.Amer. nes','0');");
E_D("replace into `ecs_cus_hg_country` values('216','601','AUS','澳大利亚','Australia','0');");
E_D("replace into `ecs_cus_hg_country` values('217','602','COK','库克群岛','Cook Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('218','603','FJI','斐济','Fiji','0');");
E_D("replace into `ecs_cus_hg_country` values('219','604','','盖比群岛','Gambier Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('220','605','','马克萨斯群岛','Marquesas Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('221','606','NRU','瑙鲁','Nauru','0');");
E_D("replace into `ecs_cus_hg_country` values('222','607','NCL','新喀里多尼亚','New Caledonia','0');");
E_D("replace into `ecs_cus_hg_country` values('223','608','VUT','瓦努阿图','Vanuatu','0');");
E_D("replace into `ecs_cus_hg_country` values('224','609','NZL','新西兰','New Zealand','0');");
E_D("replace into `ecs_cus_hg_country` values('225','610','NFK','诺福克岛','Norfolk Island','0');");
E_D("replace into `ecs_cus_hg_country` values('226','611','PNG','巴布亚新几内亚','Papua New Guinea','0');");
E_D("replace into `ecs_cus_hg_country` values('227','612','','社会群岛','Society Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('228','613','SLB','所罗门群岛','Solomon Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('229','614','TON','汤加','Tonga','0');");
E_D("replace into `ecs_cus_hg_country` values('230','615','','土阿莫土群岛','Tuamotu Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('231','616','','土布艾群岛','Tubai Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('232','617','WSM','萨摩亚','Samoa','0');");
E_D("replace into `ecs_cus_hg_country` values('233','618','KIR','基里巴斯','Kiribati','0');");
E_D("replace into `ecs_cus_hg_country` values('234','619','TUV','图瓦卢','Tuvalu','0');");
E_D("replace into `ecs_cus_hg_country` values('235','620','FSM','密克罗尼西亚联邦','Micronesia, Fs','0');");
E_D("replace into `ecs_cus_hg_country` values('236','621','MHL','马绍尔群岛','Marshall Islands','0');");
E_D("replace into `ecs_cus_hg_country` values('237','622','PLW','帕劳','Palau','0');");
E_D("replace into `ecs_cus_hg_country` values('238','623','PYF','法属波利尼西亚','French Polynesia','0');");
E_D("replace into `ecs_cus_hg_country` values('239','625','WLF','瓦利斯和浮图纳','Wallis and Futuna','0');");
E_D("replace into `ecs_cus_hg_country` values('240','699','','大洋洲其他国家(地区)','Oth. Ocean. nes','0');");
E_D("replace into `ecs_cus_hg_country` values('241','701','','国(地)别不详','Countries(reg.) unknown','0');");
E_D("replace into `ecs_cus_hg_country` values('242','702','','联合国及机构和国际组织','UN and oth. int''l  org.','0');");
E_D("replace into `ecs_cus_hg_country` values('243','999','','中性包装原产国别','Conutries of Neutral Package','0');");
E_D("replace into `ecs_cus_hg_country` values('244','111','222','333','444','0');");

require("../../inc/footer.php");
?>